import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedWeeklytrendWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedBack_GreyWidget3.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedHorizontal_GraphsRedDownWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedRectangleWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/Generated3_Elements_Circled_NavigationWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedPointsTextWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedImage16Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedpointhistorywidget/generated/GeneratedRadial_ProgressWidget.dart';

/* Frame Point History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPointHistoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 774.0,
                child: GeneratedRectangleWidget4(),
              ),
              Positioned(
                left: 21.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 184.0,
                child: GeneratedRadial_ProgressWidget(),
              ),
              Positioned(
                left: 241.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 124.1961441040039,
                height: 43.75862121582031,
                child: GeneratedPointsTextWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 47.0,
                child: GeneratedImage7Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 276.0,
                child: GeneratedImage16Widget(),
              ),
              Positioned(
                left: 25.279996871948242,
                top: 32.96574783325195,
                right: null,
                bottom: null,
                width: 68.4666519165039,
                height: 19.979244232177734,
                child: GeneratedBack_GreyWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget1(),
              ),
              Positioned(
                left: 86.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 25.0,
                child: GeneratedWeeklytrendWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedHorizontal_GraphsRedDownWidget(),
              )
            ]),
      ),
    ));
  }
}
