import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedHeadingWidget11.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedNext_ButtonWidget3.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedLetsintroduceWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedRectangleWidget26.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedName_FieldWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedHeadingWidget10.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedNumber_FieldWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup3widget/generated/GeneratedPopup_FromSMS2Widget.dart';

/* Frame Sign up 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignup3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 395.0,
      height: 770.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 34, 52, 60),
              ),
            ),
            Positioned(
              left: 12.0,
              top: 32.0,
              right: null,
              bottom: null,
              width: 174.0,
              height: 30.0,
              child: GeneratedHeadingWidget10(),
            ),
            Positioned(
              left: 31.0,
              top: 337.0,
              right: null,
              bottom: null,
              width: 347.0,
              height: 54.0,
              child: GeneratedName_FieldWidget(),
            ),
            Positioned(
              left: 31.0,
              top: 364.0,
              right: null,
              bottom: null,
              width: 315.0,
              height: 58.0,
              child: GeneratedNext_ButtonWidget3(),
            ),
            Positioned(
              left: 29.0,
              top: 142.0,
              right: null,
              bottom: null,
              width: 211.0,
              height: 55.0,
              child: GeneratedHeadingWidget11(),
            ),
            Positioned(
              left: 30.54666519165039,
              top: 195.0,
              right: null,
              bottom: null,
              width: 187.38668823242188,
              height: 31.0,
              child: GeneratedLetsintroduceWidget2(),
            ),
            Positioned(
              left: 29.0,
              top: 283.0,
              right: null,
              bottom: null,
              width: 427.0,
              height: 54.0,
              child: GeneratedNumber_FieldWidget(),
            ),
            Positioned(
              left: 3.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 392.0,
              height: 770.0,
              child: GeneratedRectangleWidget26(),
            ),
            Positioned(
              left: 0.0,
              top: -41.0,
              right: null,
              bottom: null,
              width: 395.0,
              height: 812.0,
              child: GeneratedPopup_FromSMS2Widget(),
            )
          ]),
    ));
  }
}
