import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedscanqrcodewidget/generated/GeneratedBack_GreyWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedscanqrcodewidget/generated/GeneratedRectangleCopy38Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedscanqrcodewidget/generated/GeneratedRectangleWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedscanqrcodewidget/generated/GeneratedImage9Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedscanqrcodewidget/generated/GeneratedRectangle9Widget.dart';

/* Frame Scan QR code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScanQRcodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 814.0,
                child: GeneratedRectangleWidget(),
              ),
              Positioned(
                left: 25.279996871948242,
                top: 32.96574783325195,
                right: null,
                bottom: null,
                width: 68.4666519165039,
                height: 19.979244232177734,
                child: GeneratedBack_GreyWidget(),
              ),
              Positioned(
                left: 13.69333267211914,
                top: 83.91282653808594,
                right: null,
                bottom: null,
                width: 363.4000549316406,
                height: 646.72412109375,
                child: GeneratedRectangleCopy38Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 213.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 279.0,
                child: GeneratedImage9Widget(),
              )
            ]),
      ),
    ));
  }
}
