import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexploredetailwidget/generated/Generated3_Elements_Circled_NavigationWidget5.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexploredetailwidget/generated/GeneratedRectangleWidget12.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexploredetailwidget/generated/GeneratedHeadingWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexploredetailwidget/generated/GeneratedMapWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexploredetailwidget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexploredetailwidget/generated/GeneratedBack_GreyWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexploredetailwidget/generated/GeneratedPathWidget70.dart';

/* Frame Explore detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploredetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 770.0,
                child: GeneratedRectangleWidget12(),
              ),
              Positioned(
                left: 36.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 55.0,
                child: GeneratedHeadingWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 334.0,
                child: GeneratedMapWidget(),
              ),
              Positioned(
                left: 324.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 28.439971923828125,
                height: 23.70690155029297,
                child: GeneratedPathWidget70(),
              ),
              Positioned(
                left: 30.44000244140625,
                top: 508.605224609375,
                right: null,
                bottom: null,
                width: 336.01336669921875,
                height: 94.394775390625,
                child: GeneratedGroup34Widget(),
              ),
              Positioned(
                left: 25.279998779296875,
                top: 32.96574783325195,
                right: null,
                bottom: null,
                width: 68.46666717529297,
                height: 19.979244232177734,
                child: GeneratedBack_GreyWidget6(),
              ),
              Positioned(
                left: -1.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget5(),
              )
            ]),
      ),
    ));
  }
}
