import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedForgotWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedName_FieldWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedForgotWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedPassword_FieldWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedSign_ButtonWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedHeadingWidget17.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedSubheadingWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedCreate_ButtonWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedCard_Picture_ButtonPictureWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedHeadingWidget16.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedwelcomewidget/generated/GeneratedCreate_ButtonWidget.dart';

/* Frame Welcome
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 34, 52, 60),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 58.0,
                child: GeneratedSign_ButtonWidget(),
              ),
              Positioned(
                left: 125.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 26.0,
                child: GeneratedForgotWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 58.0,
                child: GeneratedCreate_ButtonWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 30.0,
                child: GeneratedHeadingWidget16(),
              ),
              Positioned(
                left: 28.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 54.0,
                child: GeneratedName_FieldWidget4(),
              ),
              Positioned(
                left: 28.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 54.0,
                child: GeneratedPassword_FieldWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 58.0,
                child: GeneratedHeadingWidget17(),
              ),
              Positioned(
                left: 97.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 31.0,
                child: GeneratedSubheadingWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 58.0,
                child: GeneratedCreate_ButtonWidget1(),
              ),
              Positioned(
                left: 125.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 26.0,
                child: GeneratedForgotWidget1(),
              ),
              Positioned(
                left: 110.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 150.0,
                child: GeneratedCard_Picture_ButtonPictureWidget6(),
              )
            ]),
      ),
    ));
  }
}
