import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/GeneratedLineWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/Generated800Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/Generated3_Elements_Circled_NavigationWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/GeneratedCalendar_EventsWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/Generated900Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/Generated780Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/GeneratedCalendar_EventsWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/GeneratedRectangleWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedweeklychartwidget/generated/GeneratedBack_GreyWidget2.dart';

/* Frame Weekly chart
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWeeklychartWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 774.0,
                child: GeneratedRectangleWidget2(),
              ),
              Positioned(
                left: 25.279996871948242,
                top: 32.96574783325195,
                right: null,
                bottom: null,
                width: 68.4666519165039,
                height: 19.979244232177734,
                child: GeneratedBack_GreyWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 210.0,
                child: GeneratedCalendar_EventsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 210.0,
                child: GeneratedCalendar_EventsWidget1(),
              ),
              Positioned(
                left: 329.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 107.89388275146484,
                height: 32.931034088134766,
                child: Generated900Widget(),
              ),
              Positioned(
                left: 330.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 107.89388275146484,
                height: 32.931034088134766,
                child: Generated800Widget(),
              ),
              Positioned(
                left: 332.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 107.89388275146484,
                height: 32.931034088134766,
                child: Generated780Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 378.14666748046875,
                height: 1.0,
                child: GeneratedLineWidget6(),
              ),
              Positioned(
                left: 36.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 82.0,
                child: GeneratedGroup37Widget(),
              )
            ]),
      ),
    ));
  }
}
