import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding3widget/generated/GeneratedRectangleWidget23.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding3widget/generated/GeneratedBodyTextWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding3widget/generated/GeneratedHeadingWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding3widget/generated/GeneratedImage19Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding3widget/generated/GeneratedSigninWidget3.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding3widget/generated/GeneratedBulletsWidget1.dart';

/* Frame Onboarding3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboarding3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -11.0,
                top: -21.0,
                right: null,
                bottom: null,
                width: 403.9999694824219,
                height: 791.0,
                child: GeneratedRectangleWidget23(),
              ),
              Positioned(
                left: 57.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 50.0,
                child: GeneratedBodyTextWidget1(),
              ),
              Positioned(
                left: 163.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 9.0,
                child: GeneratedBulletsWidget1(),
              ),
              Positioned(
                left: 171.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 31.0,
                child: GeneratedHeadingWidget6(),
              ),
              Positioned(
                left: 76.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 488.0,
                child: GeneratedImage19Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 653.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 58.0,
                child: GeneratedSigninWidget3(),
              )
            ]),
      ),
    ));
  }
}
