import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding1widget/generated/GeneratedSigninWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding1widget/generated/GeneratedImage17Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding1widget/generated/GeneratedBulletsWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding1widget/generated/GeneratedRectangleWidget24.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding1widget/generated/GeneratedHeadingWidget7.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding1widget/generated/GeneratedBodyTextWidget2.dart';

/* Frame Onboarding1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboarding1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -21.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 791.0,
                child: GeneratedRectangleWidget24(),
              ),
              Positioned(
                left: 62.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 50.0,
                child: GeneratedBodyTextWidget2(),
              ),
              Positioned(
                left: 168.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 9.0,
                child: GeneratedBulletsWidget2(),
              ),
              Positioned(
                left: 40.0,
                top: 653.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 58.0,
                child: GeneratedSigninWidget4(),
              ),
              Positioned(
                left: 65.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 28.0,
                child: GeneratedHeadingWidget7(),
              ),
              Positioned(
                left: 87.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 452.0,
                child: GeneratedImage17Widget(),
              )
            ]),
      ),
    ));
  }
}
