import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedPointsTextWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedCategories_Pictures1BlueWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedCard_Picture_ButtonPictureWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedTostartworkingcopyWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/Generated3_Elements_Circled_NavigationWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedLevelupbarWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedNameTamagoWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedCategories_Pictures1BlueWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedBack_GreyWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedCategories_Pictures1BlueWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedTostartworkingcopyWidget3.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedRectangleWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedgameprofile2widget/generated/GeneratedTostartworkingcopyWidget1.dart';

/* Frame Game Profile 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGameProfile2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 774.0,
                child: GeneratedRectangleWidget6(),
              ),
              Positioned(
                left: 37.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 59.0,
                child: GeneratedPointsTextWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 337.586669921875,
                height: 31.932815551757812,
                child: GeneratedLevelupbarWidget(),
              ),
              Positioned(
                left: 25.279996871948242,
                top: 32.96574783325195,
                right: null,
                bottom: null,
                width: 68.4666519165039,
                height: 19.979244232177734,
                child: GeneratedBack_GreyWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget2(),
              ),
              Positioned(
                left: 103.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 190.0,
                child: GeneratedCard_Picture_ButtonPictureWidget(),
              ),
              Positioned(
                left: 123.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 30.0,
                child: GeneratedNameTamagoWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 57.0,
                child: GeneratedCategories_Pictures1BlueWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 22.0,
                child: GeneratedTostartworkingcopyWidget1(),
              ),
              Positioned(
                left: 168.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 57.0,
                child: GeneratedCategories_Pictures1BlueWidget1(),
              ),
              Positioned(
                left: 188.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 22.0,
                child: GeneratedTostartworkingcopyWidget2(),
              ),
              Positioned(
                left: 283.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 57.0,
                child: GeneratedCategories_Pictures1BlueWidget2(),
              ),
              Positioned(
                left: 292.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 22.0,
                child: GeneratedTostartworkingcopyWidget3(),
              )
            ]),
      ),
    ));
  }
}
