import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedusersqrcodewidget/generated/GeneratedImage21Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedusersqrcodewidget/generated/GeneratedBack_GreyWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedusersqrcodewidget/generated/GeneratedRectangleWidget1.dart';

/* Frame User's QR code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUsersQRcodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 814.0,
                child: GeneratedRectangleWidget1(),
              ),
              Positioned(
                left: 25.279996871948242,
                top: 32.96574783325195,
                right: null,
                bottom: null,
                width: 68.4666519165039,
                height: 19.979244232177734,
                child: GeneratedBack_GreyWidget1(),
              ),
              Positioned(
                left: 38.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 324.0,
                child: GeneratedImage21Widget(),
              )
            ]),
      ),
    ));
  }
}
