import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedPathWidget105.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedSigninWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedBarcelonaWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedRectangleWidget16.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/Generated3_Elements_Circled_NavigationWidget7.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedImage12Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedHeadingWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedBarcelonaWidget5.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedRectangleWidget17.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptiondetailwidget/generated/GeneratedBack_GreyWidget7.dart';

/* Frame Redemption detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedemptiondetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 812.0,
                child: GeneratedRectangleWidget17(),
              ),
              Positioned(
                left: 48.45332717895508,
                top: 439.5433349609375,
                right: null,
                bottom: null,
                width: 307.4667053222656,
                height: 88.90972900390625,
                child: GeneratedBarcelonaWidget5(),
              ),
              Positioned(
                left: 41.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 54.0,
                child: GeneratedBarcelonaWidget6(),
              ),
              Positioned(
                left: 41.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 55.0,
                child: GeneratedHeadingWidget4(),
              ),
              Positioned(
                left: 320.2133483886719,
                top: 80.91593170166016,
                right: null,
                bottom: null,
                width: 28.439971923828125,
                height: 23.706893920898438,
                child: GeneratedPathWidget105(),
              ),
              Positioned(
                left: 43.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 288.0,
                child: GeneratedImage12Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 590.3866577148438,
                right: null,
                bottom: null,
                width: 335.0,
                height: 57.93975830078125,
                child: GeneratedSigninWidget1(),
              ),
              Positioned(
                left: 25.279996871948242,
                top: 32.96574783325195,
                right: null,
                bottom: null,
                width: 68.46666717529297,
                height: 19.979244232177734,
                child: GeneratedBack_GreyWidget7(),
              ),
              Positioned(
                left: 4.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget7(),
              )
            ]),
      ),
    ));
  }
}
