import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedName_FieldWidget3.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedLetsintroduceWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedHeadingWidget14.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedCreatePass_FieldWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedName_FieldWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedHeadingWidget15.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedNext_ButtonWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup1widget/generated/GeneratedCreatePass_FieldWidget.dart';

/* Frame Sign up 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignup1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 34, 52, 60),
                ),
              ),
              Positioned(
                left: 12.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 30.0,
                child: GeneratedHeadingWidget14(),
              ),
              Positioned(
                left: 31.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 54.0,
                child: GeneratedName_FieldWidget2(),
              ),
              Positioned(
                left: 29.0,
                top: 264.5689697265625,
                right: null,
                bottom: null,
                width: 347.0,
                height: 51.2069091796875,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 54.0,
                child: GeneratedName_FieldWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 58.0,
                child: GeneratedNext_ButtonWidget6(),
              ),
              Positioned(
                left: 29.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 55.0,
                child: GeneratedHeadingWidget15(),
              ),
              Positioned(
                left: 30.54667091369629,
                top: 196.0,
                right: null,
                bottom: null,
                width: 187.38665771484375,
                height: 31.0,
                child: GeneratedLetsintroduceWidget4(),
              ),
              Positioned(
                left: 29.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 54.0,
                child: GeneratedCreatePass_FieldWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 54.0,
                child: GeneratedCreatePass_FieldWidget1(),
              )
            ]),
      ),
    ));
  }
}
