import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding2widget/generated/GeneratedHeadingWidget5.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding2widget/generated/GeneratedRectangleWidget22.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding2widget/generated/GeneratedBulletsWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding2widget/generated/GeneratedBodyTextWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding2widget/generated/GeneratedImage18Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedonboarding2widget/generated/GeneratedSigninWidget2.dart';

/* Frame Onboarding2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboarding2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -21.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 791.0,
                child: GeneratedRectangleWidget22(),
              ),
              Positioned(
                left: 58.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 74.0,
                child: GeneratedBodyTextWidget(),
              ),
              Positioned(
                left: 58.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 28.0,
                child: GeneratedHeadingWidget5(),
              ),
              Positioned(
                left: 164.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 9.0,
                child: GeneratedBulletsWidget(),
              ),
              Positioned(
                left: 79.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 455.0,
                child: GeneratedImage18Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 653.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 58.0,
                child: GeneratedSigninWidget2(),
              )
            ]),
      ),
    ));
  }
}
