import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup4widget/generated/GeneratedRectangleWidget25.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup4widget/generated/GeneratedLetsintroduceWidget1.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup4widget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup4widget/generated/GeneratedHeadingWidget8.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup4widget/generated/GeneratedCard_Picture_ButtonPictureWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsignup4widget/generated/GeneratedHeadingWidget9.dart';

/* Frame Sign up 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignup4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 774.0,
                child: GeneratedRectangleWidget25(),
              ),
              Positioned(
                left: 122.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 150.0,
                child: GeneratedCard_Picture_ButtonPictureWidget4(),
              ),
              Positioned(
                left: 29.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 55.0,
                child: GeneratedHeadingWidget8(),
              ),
              Positioned(
                left: 12.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 30.0,
                child: GeneratedHeadingWidget9(),
              ),
              Positioned(
                left: 30.546630859375,
                top: 195.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 31.0,
                child: GeneratedLetsintroduceWidget1(),
              ),
              Positioned(
                left: 122.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 150.0,
                child: GeneratedGroup35Widget(),
              )
            ]),
      ),
    ));
  }
}
