import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptioncardswidget/generated/Generated3_Elements_Circled_NavigationWidget8.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptioncardswidget/generated/GeneratedRectangleWidget19.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptioncardswidget/generated/GeneratedRectangleWidget20.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptioncardswidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptioncardswidget/generated/GeneratedCategories2Widget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedredemptioncardswidget/generated/GeneratedImage24Widget.dart';

/* Frame Redemption cards
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedemptioncardsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 770.0,
                child: GeneratedRectangleWidget20(),
              ),
              Positioned(
                left: 32.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 137.0,
                child: GeneratedCategories2Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 508.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget8(),
              ),
              Positioned(
                left: 265.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 20.0,
                child: GeneratedImage24Widget(),
              )
            ]),
      ),
    ));
  }
}
