import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexplorecardswidget/generated/Generated3Huge_PicturesWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexplorecardswidget/generated/Generated3_Elements_Circled_NavigationWidget6.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexplorecardswidget/generated/GeneratedRectangleWidget14.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedexplorecardswidget/generated/GeneratedIPhoneXStatus_BarWidget.dart';

/* Frame Explore cards
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExplorecardsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 770.0,
                child: GeneratedRectangleWidget14(),
              ),
              Positioned(
                left: -65.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIPhoneXStatus_BarWidget(),
              ),
              Positioned(
                left: -240.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 875.0,
                height: 587.0,
                child: Generated3Huge_PicturesWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget6(),
              )
            ]),
      ),
    ));
  }
}
