import 'package:flutter/material.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsettingswidget/generated/Generated3_Elements_Circled_NavigationWidget4.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsettingswidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsettingswidget/generated/GeneratedMenuWidget2.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsettingswidget/generated/GeneratedMenu_SwitchesWidget.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsettingswidget/generated/GeneratedRectangleWidget10.dart';
import 'package:flutterapp/city_20hunter_20__20android_205app/generatedsettingswidget/generated/GeneratedMenu_SwitchesWidget1.dart';

/* Frame Settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 395.0,
        height: 770.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 775.0,
                child: GeneratedRectangleWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 394.0,
                height: 210.0,
                child: GeneratedMenuWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 394.0,
                height: 91.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 394.0,
                height: 68.0,
                child: GeneratedMenu_SwitchesWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 394.0,
                height: 68.0,
                child: GeneratedMenu_SwitchesWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: Generated3_Elements_Circled_NavigationWidget4(),
              )
            ]),
      ),
    ));
  }
}
